version: "3.8"
services:
  reverse-proxy:
    image: traefik:v2.6.1
    # enables the web ui and tells Traefik to listen to Docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
    networks:
      - traefik

  account-api:
    build:
      dockerfile: Dockerfile
      context: ../account-api
      target: dev
    image: account-api
    env_file:
      - ../account-api/.env.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account-api.entrypoints=web"
      - "traefik.http.routers.account-api.rule=PathPrefix(`/api/account`)"
      - "traefik.http.services.account-api.loadbalancer.server.port=3000"
    environment:
      - ENV=dev
    volumes:
      - ../account-api/.:/opt/app/account-api
    depends_on:
      - reverse-proxy
    networks:
      - traefik

networks:
  traefik:
volumes:
  traefik-ssl-certs:
    driver: local